// frontend/src/countries.js

const countries = [
    { label: "Afghanistan", code: "af" },
    { label: "Albania", code: "al" },
    { label: "Algeria", code: "dz" },
    { label: "Andorra", code: "ad" },
    { label: "Angola", code: "ao" },
    { label: "Antigua and Barbuda", code: "ag" },
    { label: "Argentina", code: "ar" },
    { label: "Armenia", code: "am" },
    { label: "Australia", code: "au" },
    { label: "Austria", code: "at" },
    { label: "Azerbaijan", code: "az" },
    { label: "Bahamas", code: "bs" },
    { label: "Bahrain", code: "bh" },
    { label: "Bangladesh", code: "bd" },
    { label: "Barbados", code: "bb" },
    { label: "Belarus", code: "by" },
    { label: "Belgium", code: "be" },
    { label: "Belize", code: "bz" },
    { label: "Benin", code: "bj" },
    { label: "Bhutan", code: "bt" },
    { label: "Bolivia (Plurinational State of)", code: "bo" },
    { label: "Bosnia and Herzegovina", code: "ba" },
    { label: "Botswana", code: "bw" },
    { label: "Brazil", code: "br" },
    { label: "Brunei Darussalam", code: "bn" },
    { label: "Bulgaria", code: "bg" },
    { label: "Burkina Faso", code: "bf" },
    { label: "Burundi", code: "bi" },
    { label: "Côte d'Ivoire", code: "ci" },
    { label: "Cabo Verde", code: "cv" },
    { label: "Cambodia", code: "kh" },
    { label: "Cameroon", code: "cm" },
    { label: "Canada", code: "ca" },
    { label: "Central African Republic", code: "cf" },
    { label: "Chad", code: "td" },
    { label: "Chile", code: "cl" },
    { label: "China", code: "cn" },
    { label: "Colombia", code: "co" },
    { label: "Comoros", code: "km" },
    { label: "Congo (Republic of the)", code: "cg" },
    { label: "Congo (Democratic Republic of the)", code: "cd" },
    { label: "Costa Rica", code: "cr" },
    { label: "Croatia", code: "hr" },
    { label: "Cuba", code: "cu" },
    { label: "Cyprus", code: "cy" },
    { label: "Czechia", code: "cz" },
    { label: "Denmark", code: "dk" },
    { label: "Djibouti", code: "dj" },
    { label: "Dominica", code: "dm" },
    { label: "Dominican Republic", code: "do" },
    { label: "Ecuador", code: "ec" },
    { label: "Egypt", code: "eg" },
    { label: "El Salvador", code: "sv" },
    { label: "Equatorial Guinea", code: "gq" },
    { label: "Eritrea", code: "er" },
    { label: "Estonia", code: "ee" },
    { label: "Eswatini", code: "sz" },
    { label: "Ethiopia", code: "et" },
    { label: "Fiji", code: "fj" },
    { label: "Finland", code: "fi" },
    { label: "France", code: "fr" },
    { label: "Gabon", code: "ga" },
    { label: "Gambia", code: "gm" },
    { label: "Georgia", code: "ge" },
    { label: "Germany", code: "de" },
    { label: "Ghana", code: "gh" },
    { label: "Greece", code: "gr" },
    { label: "Grenada", code: "gd" },
    { label: "Guatemala", code: "gt" },
    { label: "Guinea", code: "gn" },
    { label: "Guinea-Bissau", code: "gw" },
    { label: "Guyana", code: "gy" },
    { label: "Haiti", code: "ht" },
    { label: "Honduras", code: "hn" },
    { label: "Hungary", code: "hu" },
    { label: "Iceland", code: "is" },
    { label: "India", code: "in" },
    { label: "Indonesia", code: "id" },
    { label: "Iran (Islamic Republic of)", code: "ir" },
    { label: "Iraq", code: "iq" },
    { label: "Ireland", code: "ie" },
    { label: "Israel", code: "il" },
    { label: "Italy", code: "it" },
    { label: "Jamaica", code: "jm" },
    { label: "Japan", code: "jp" },
    { label: "Jordan", code: "jo" },
    { label: "Kazakhstan", code: "kz" },
    { label: "Kenya", code: "ke" },
    { label: "Kiribati", code: "ki" },
    { label: "Korea (Republic of)", code: "kr" },
    { label: "Kuwait", code: "kw" },
    { label: "Kyrgyzstan", code: "kg" },
    { label: "Lao People's Democratic Republic", code: "la" },
    { label: "Latvia", code: "lv" },
    { label: "Lebanon", code: "lb" },
    { label: "Lesotho", code: "ls" },
    { label: "Liberia", code: "lr" },
    { label: "Libya", code: "ly" },
    { label: "Liechtenstein", code: "li" },
    { label: "Lithuania", code: "lt" },
    { label: "Luxembourg", code: "lu" },
    { label: "Madagascar", code: "mg" },
    { label: "Malawi", code: "mw" },
    { label: "Malaysia", code: "my" },
    { label: "Maldives", code: "mv" },
    { label: "Mali", code: "ml" },
    { label: "Malta", code: "mt" },
    { label: "Marshall Islands", code: "mh" },
    { label: "Mauritania", code: "mr" },
    { label: "Mauritius", code: "mu" },
    { label: "Mexico", code: "mx" },
    { label: "Micronesia (Federated States of)", code: "fm" },
    { label: "Moldova (Republic of)", code: "md" },
    { label: "Monaco", code: "mc" },
    { label: "Mongolia", code: "mn" },
    { label: "Montenegro", code: "me" },
    { label: "Morocco", code: "ma" },
    { label: "Mozambique", code: "mz" },
    { label: "Myanmar", code: "mm" },
    { label: "Namibia", code: "na" },
    { label: "Nauru", code: "nr" },
    { label: "Nepal", code: "np" },
    { label: "Netherlands", code: "nl" },
    { label: "New Zealand", code: "nz" },
    { label: "Nicaragua", code: "ni" },
    { label: "Niger", code: "ne" },
    { label: "Nigeria", code: "ng" },
    { label: "North Macedonia", code: "mk" },
    { label: "Norway", code: "no" },
    { label: "Oman", code: "om" },
    { label: "Pakistan", code: "pk" },
    { label: "Palau", code: "pw" },
    { label: "Palestine, State of", code: "ps" },
    { label: "Panama", code: "pa" },
    { label: "Papua New Guinea", code: "pg" },
    { label: "Paraguay", code: "py" },
    { label: "Peru", code: "pe" },
    { label: "Philippines", code: "ph" },
    { label: "Poland", code: "pl" },
    { label: "Portugal", code: "pt" },
    { label: "Qatar", code: "qa" },
    { label: "Romania", code: "ro" },
    { label: "Russian Federation", code: "ru" },
    { label: "Rwanda", code: "rw" },
    { label: "Saint Kitts and Nevis", code: "kn" },
    { label: "Saint Lucia", code: "lc" },
    { label: "Saint Vincent and the Grenadines", code: "vc" },
    { label: "Samoa", code: "ws" },
    { label: "San Marino", code: "sm" },
    { label: "Sao Tome and Principe", code: "st" },
    { label: "Saudi Arabia", code: "sa" },
    { label: "Senegal", code: "sn" },
    { label: "Serbia", code: "rs" },
    { label: "Seychelles", code: "sc" },
    { label: "Sierra Leone", code: "sl" },
    { label: "Singapore", code: "sg" },
    { label: "Slovakia", code: "sk" },
    { label: "Slovenia", code: "si" },
    { label: "Solomon Islands", code: "sb" },
    { label: "Somalia", code: "so" },
    { label: "South Africa", code: "za" },
    { label: "South Sudan", code: "ss" },
    { label: "Spain", code: "es" },
    { label: "Sri Lanka", code: "lk" },
    { label: "Sudan", code: "sd" },
    { label: "Suriname", code: "sr" },
    { label: "Sweden", code: "se" },
    { label: "Switzerland", code: "ch" },
    { label: "Syrian Arab Republic", code: "sy" },
    { label: "Taiwan, Province of China", code: "tw" },
    { label: "Tajikistan", code: "tj" },
    { label: "Tanzania, United Republic of", code: "tz" },
    { label: "Thailand", code: "th" },
    { label: "Timor-Leste", code: "tl" },
    { label: "Togo", code: "tg" },
    { label: "Tonga", code: "to" },
    { label: "Trinidad and Tobago", code: "tt" },
    { label: "Tunisia", code: "tn" },
    { label: "Turkey", code: "tr" },
    { label: "Turkmenistan", code: "tm" },
    { label: "Tuvalu", code: "tv" },
    { label: "Uganda", code: "ug" },
    { label: "Ukraine", code: "ua" },
    { label: "United Arab Emirates", code: "ae" },
    { label: "United Kingdom of Great Britain and Northern Ireland", code: "gb" },
    { label: "United States of America", code: "us" },
    { label: "Uruguay", code: "uy" },
    { label: "Uzbekistan", code: "uz" },
    { label: "Vanuatu", code: "vu" },
    { label: "Venezuela (Bolivarian Republic of)", code: "ve" },
    { label: "Viet Nam", code: "vn" },
    { label: "Yemen", code: "ye" },
    { label: "Zambia", code: "zm" },
    { label: "Zimbabwe", code: "zw" }
];

export default countries;
